### ISSUE TITLE
Payment plans page

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/site-mvp#237] opened 2015-07-07 14:18 UTC
We need more information on the payments page to inform applicants. Something like this :

http://wegotcoders.com/trainee-web-developer-course/price-plans

**Comment by spike01** [comment] 2015-07-07 14:22
What additional information? The Wegotcoders stuff is mostly irrelevant as we don't do instalments nor do we provide accommodation, refund policy is "NO" and we don't have KPIs for our students.

**Comment by nikeshashar** [comment] 2015-07-14 00:33
Cash / Female discount / Payment dates & deadlines / terms / PCDL / Student Funder / Finance my Future / Credit cards / Transferwise / GoCardless / Paypal / Refunds / Cancellations / Non refundable deposits / Commitment to the course /

**Comment by pitchinvasion** [comment] 2015-07-14 12:03
Can you wireframe this Nikesh?

**Comment by nikeshashar** [comment] 2015-07-14 22:44
Ruben has already. Will get the ticket info off him.

**Comment by pitchinvasion** [comment] 2015-07-16 17:54
duplicate of #200

**Closed** 2015-07-16 17:54 UTC
Labels: blocked, content
